### ISSUE TITLE
复杂度过高导致出现问题

### ISSUE THREAD

**Issue by wyapx** [saltedfishclub/PolarCore#15]
你就不能做nocode support吗？写Java太麻烦了，几百行代码才实现一个功能

**Comment by NaturalSelect** [comment]
谢谢兄弟，有被笑到

**Comment by JoinChang** [comment]
**NC牛逼，自然牛逼**

**Comment by NaturalSelect** [comment]
lxns nb

**Comment by wyapx** [comment]
@NaturalSelect 建议你也支持一下nocode，C++的编写难度过高，不适宜新手（

**Comment by JoinChang** [comment]
> @NaturalSelect 建议你也支持一下nocode，C++的编写难度过高，不适宜新手（

我就垃圾了，没有开源项目

**Comment by NaturalSelect** [comment]
建议看看stdx的定位，STL拓展

**Comment by wyapx** [comment]
> 建议看看stdx的定位，STL拓展

我怀疑你在歧视臭打游戏的人

**Comment by iceBear67** [comment]
你脑子不好使，不负责

**Comment by NaturalSelect** [comment]
> > 建议看看stdx的定位，STL拓展
> 
> 我怀疑你在歧视臭打游戏的人

辣你能扮莲华吗？
