### ISSUE TITLE
User and Group took on too many responsibilities

### ISSUE THREAD

**Issue by NaturalSelect** [saltedfishclub/PolarCore#23]
Follow SRP.
The classes took on too many responsibilities and should be refactor.
Static method such as https://github.com/saltedfishclub/PolarCore/blob/c6af1affe323b1291eca73d505a20ad4fb5ae0b7/src/main/java/cc/sfclub/user/User.java#L85
should not be one of responsiblity of "User".
You may need a interface like "UserManager" and a implementor.

**Comment by iceBear67** [comment]
26e29cdbbaaaca513da23f3f803231647a14ace0
